# convert_columns = {
#     "level_1": "organization",
#     # "level_2": "jobs",
#     "姓名（手工录入）": "nickname",
#     "性别": "gender",
#     "出生日期": "birthday",
#     "年龄": "(YEAR(NOW())-birthday) as year",
#     "民族": "national",
#     # "籍贯": "native_place",
#     "政治面貌": "politics_status",
#     # "入党时间": "entry_party_date",
#     "Unnamed: 6": "party_position",  # 党内职务
#     "婚姻状况": "marriage",
#     "生育状况": "fertility",
#     "是否在工作地安家": "is_workplace_settle_down",
#     "回家频次": "home_frequency",
#     "是否与配偶两地分居": "is_separation",
#     "与配偶见面频次": "spouses_see_frequency",
#
#     "配偶工作情况": "spouses_work_condition",
#     "是否与小孩共同生活": "is_with_children_live",  # 党内职务
#     "小孩见面频次": "see_children_frequency",
#     "是否本地人": "is_native",
#     "父母是否跟随": "is_parents_follow",
#     "住房情况": "housing_situation",
#     "出行情况": "travel_situation",
#     "第一学历": "first_education",
#
#     "取得学位": "first_degree",
#     "毕业时间": "first_graduation_date",  # 党内职务
#     "毕业院校": "first_graduate_school",
#     "所学专业": "first_major",
#     "最高学历": "master_education",
#     "取得学位.1": "master_degree",
#     "毕业时间.1": "master_graduation_date",
#     "毕业院校.1": "master_graduate_school",
#     "所学专业.1": "master_major",
#     "进入烟草时间": "entry_tobacco_date",
#     "行业工作年限": "(YEAR(NOW())-entry_tobacco_date) as work_year",  # 党内职务
#     "职务": "work_position",
#     "岗位类别": "work_category",
#     "环节": "work_link",
#     "基层一线工作累计时间（月）": "basic_work_month",
#     "上挂借用累计时间（月）": "hang_on_borrow_month",
#     "任现级时间": "present_work_month",
#
#     "专业技术资格": "professional_qualifications",
#     "等级": "professional_level",  # 党内职务
#     "取证时间": "certificate_date",
#     "是否聘任": "is_employment",
#     "其他专业技术资格": "other_professional_qualifications",
#     "等级.1": "other_professional_level",
#     "取证时间.1": "other_certificate_date",
#     "是否聘任.1": "is_other_employment",
#     "行业特有专业技能资格1": "special_skills",
#     "等级.2": "special_skills_level",  # 党内职务
#     "取证时间.2": "skills_certificate_date",
#     "是否聘任.2": "is_skills_employment",
#     "行业特有专业技能资格2": "other_special_skills",
#     "等级.3": "other_special_skills_level",
#     "取证时间.3": "other_skills_certificate_date",
#     "是否聘任.3": "is_other_skills_employment",
#     "资格1": "general_social_qualification",
#     "资格2": "other_general_social_qualification",
#
#     # "培训经历（手工录入，分项填写）": "trained_experience",
#     "单位内部培训次数": "organization_training_times",
#     "省局培训次数": "province_training_times",
#     "国家局培训次数": "countries_training_times",
#     "行业外培训次数": "industry_outside_times",
#     "培训总次数": "sum_training_times",
#     # "工作经历（手工录入，分项填写）": "work_experience",
#     "参加市局竞赛、活动次数": "join_city_competition",
#     "参加政府竞赛、活动次数": "join_government_competition",
#     "参加省局及以上竞赛、活动次数": "join_province_competition",
#     "参加各类竞赛、活动总次数": "join_all_kinds_competition",
#     "参与竞赛、大型活动、科技创新情况（手工录入，分项填写）": "join_situation",
#     "获奖、荣誉、科技成果（手工录入，分项填写）": "winning_situation",
#     "《湖北烟草》、《东方烟草报》、国家局网站等媒体发表作品篇数（第一作者）": "first_author_times",
#     "期刊发表论文篇数": "paper_number",
#     "其中核心期刊篇数": "core_paper_number",
#     # "行业内亲属关系（手工录入，分项填写）": "industry_relatives",
#     # "亲属经商办企业情况（手工录入，分项填写）": "relatives_business",
#     # "亲属在与烟草行业有业务关联的单位从业情况（手工录入，分项填写）": "relatives_relevance_organization",
#     # "违纪违规受处分情况（手工录入，分项填写）": "punishment_situation",
#     # "家庭成员基本信息（手工录入，分项填写）": "family_members",
# }


convert_columns = {
    "level_1": "organization",
    "level_2": "jobs",
    "姓名（手工录入）": "nickname",
    "性别": "gender",
    "出生日期": "birthday",
    "年龄": "(YEAR(NOW())-birthday) as year",
    "民族": "national",
    "籍贯": "native_place",
    "政治面貌": "politics_status",
    "入党时间": "entry_party_date",
    "Unnamed: 8": "party_position",  # 党内职务
    "婚姻状况": "marriage",
    "生育状况": "fertility",
    "是否在工作地安家": "is_workplace_settle_down",
    "回家频次": "home_frequency",
    "是否与配偶两地分居": "is_separation",
    "与配偶见面频次": "spouses_see_frequency",

    "配偶工作情况": "spouses_work_condition",
    "是否与小孩共同生活": "is_with_children_live",  # 党内职务
    "小孩见面频次": "see_children_frequency",
    "是否本地人": "is_native",
    "父母是否跟随": "is_parents_follow",
    "住房情况": "housing_situation",
    "出行情况": "travel_situation",
    "第一学历": "first_education",

    "取得学位": "first_degree",
    "毕业时间": "first_graduation_date",  # 党内职务
    "毕业院校": "first_graduate_school",
    "所学专业": "first_major",
    "最高学历": "master_education",
    "取得学位.1": "master_degree",
    "毕业时间.1": "master_graduation_date",
    "毕业院校.1": "master_graduate_school",
    "所学专业.1": "master_major",
    "进入烟草时间": "entry_tobacco_date",
    "行业工作年限": "(YEAR(NOW())-entry_tobacco_date) as work_year",  # 党内职务
    "职务": "work_position",
    "岗位类别": "work_category",
    "环节": "work_link",
    "基层一线工作累计时间（月）": "basic_work_month",
    "上挂借用累计时间（月）": "hang_on_borrow_month",
    "任现级时间": "present_work_month",

    "专业技术资格": "professional_qualifications",
    "等级": "professional_level",  # 党内职务
    "取证时间": "certificate_date",
    "是否聘任": "is_employment",
    "其他专业技术资格": "other_professional_qualifications",
    "等级.1": "other_professional_level",
    "取证时间.1": "other_certificate_date",
    "是否聘任.1": "is_other_employment",
    "行业特有专业技能资格1": "special_skills",
    "等级.2": "special_skills_level",  # 党内职务
    "取证时间.2": "skills_certificate_date",
    "是否聘任.2": "is_skills_employment",
    "行业特有专业技能资格2": "other_special_skills",
    "等级.3": "other_special_skills_level",
    "取证时间.3": "other_skills_certificate_date",
    "是否聘任.3": "is_other_skills_employment",
    "资格1": "general_social_qualification",
    "资格2": "other_general_social_qualification",

    "培训经历（手工录入，分项填写）": "trained_experience",
    "单位内部培训次数": "organization_training_times",
    "省局培训次数": "province_training_times",
    "国家局培训次数": "countries_training_times",
    "行业外培训次数": "industry_outside_times",
    "培训总次数": "sum_training_times",
    "工作经历（手工录入，分项填写）": "work_experience",
    "参加市局竞赛、活动次数": "join_city_competition",
    "参加政府竞赛、活动次数": "join_government_competition",
    "参加省局及以上竞赛、活动次数": "join_province_competition",
    "参加各类竞赛、活动总次数": "join_all_kinds_competition",
    "参与竞赛、大型活动、科技创新情况（手工录入，分项填写）": "join_situation",
    "获奖、荣誉（手工录入，分项填写）": "winning_situation",
    "科技成果（手工录入，分项填写）": "science_achievements",
    "《湖北烟草》、《东方烟草报》、国家局网站等媒体发表作品篇数（第一作者）": "first_author_times",
    "期刊发表论文篇数": "paper_number",
    "其中核心期刊篇数": "core_paper_number",
    "行业内亲属关系（手工录入，分项填写）": "industry_relatives",
    "亲属经商办企业情况（手工录入，分项填写）": "relatives_business",
    "亲属在与烟草行业有业务关联的单位从业情况（手工录入，分项填写）": "relatives_relevance_organization",
    "违纪违规受处分情况（手工录入，分项填写）": "punishment_situation",
    "家庭成员基本信息（手工录入，分项填写）": "family_members",
}
